export enum socketEvent {
  TIME = 'TIME',

  JOIN_EXAM = 'JOIN_EXAM',
  LEAVE_EXAM = 'LEAVE_EXAM',
  ADD_PEER = 'ADD_PEER',
  REMOVE_PEER = 'REMOVE_PEER',
  RELAY_ICE_CANDIDATE = 'RELAY_ICE_CANDIDATE',
  ICE_CANDIDATE = 'ICE_CANDIDATE',
  RELAY_SESSION_DESCRIPTION = 'RELAY_SESSION_DESCRIPTION',
  SESSION_DESCRIPTION = 'SESSION_DESCRIPTION',
  PEER_STATUS = 'PEER_STATUS',
  ADD_TRANSCRIPT = 'ADD_TRANSCRIPT',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
}
